server {
    listen 9000;
    server_name 127.0.0.1 localhost host.docker.internal;
    index index.php index.html;
    root /var/www/www-data/webgametop/public;

    # Логирование
    access_log /var/log/nginx/webgametop.access.log main;
    error_log /var/log/nginx/webgametop.error.log warn;

    # Основная конфигурация
    location / {
        try_files $uri $uri/ /index.php?$query_string;
        limit_req zone=general burst=20 nodelay;
    }

    include /etc/nginx/common.conf;
}
